#!/usr/bin/env bash
# AutoVless: turn this VPS into a private, fixed-IP exit for AI sites
# (ChatGPT, Gemini, Claude, ...). The Cloudflare Worker sends AI traffic here
# (AI_PROXY_IP) and it leaves the internet from THIS server's IP, always the same
# address, in this server's country. Only AI hostnames are allowed through, so it
# is not an open proxy.
#
# Usage: sudo bash scripts/setup-ai-relay.sh [port]      (default port 8443)
# The server must be OUTSIDE Iran (Germany, Netherlands, US, ...).
set -euo pipefail

PORT="${1:-8443}"
TARGET="${AUTOVLESS_DIR:-/opt/autovless}"
ENV_FILE="${TARGET}/.env"

green() { printf '\033[0;32m%s\033[0m\n' "$1"; }
red()   { printf '\033[0;31m%s\033[0m\n' "$1"; }
info()  { printf '\033[0;36m%s\033[0m\n' "$1"; }

[[ $EUID -eq 0 ]] || { red "Run as root: sudo bash $0"; exit 1; }

MY_IP="$(curl -4 -fsS https://api.ipify.org)"
COUNTRY="$(curl -fsS "https://ipinfo.io/${MY_IP}/country" 2>/dev/null | tr -d '[:space:]' || true)"
info "server ip ${MY_IP}, country ${COUNTRY:-unknown}"
case "${COUNTRY}" in
  IR|RU|CN|CU|SY|KP|BY|VE) red "This server is in ${COUNTRY}. AI sites block that region. Use a VPS in DE/NL/US/..."; exit 1;;
esac

info "1/4 installing nginx stream module (without starting it on port 80)"
# Keep apt from starting nginx: Caddy already owns ports 80/443.
printf '#!/bin/sh\nexit 101\n' > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d
apt-get update -y
apt-get install -y nginx libnginx-mod-stream || apt-get install -y nginx-full
rm -f /usr/sbin/policy-rc.d
rm -f /etc/nginx/sites-enabled/default

info "2/4 writing the SNI allow-list relay on port ${PORT}"
mkdir -p /etc/nginx/stream.d
if ! grep -q 'stream.d' /etc/nginx/nginx.conf; then
  printf '\nstream {\n    include /etc/nginx/stream.d/*.conf;\n}\n' >> /etc/nginx/nginx.conf
fi

cat > /etc/nginx/stream.d/autovless-ai.conf <<EOF
# Generated by AutoVless setup-ai-relay.sh
# Reads the TLS SNI and forwards only AI hostnames. Everything else is dropped.
map \$ssl_preread_server_name \$ai_backend {
    hostnames;
    default                     127.0.0.1:9;

    # OpenAI / ChatGPT / Sora
    .openai.com                 \$ssl_preread_server_name:443;
    .chatgpt.com                \$ssl_preread_server_name:443;
    .oaistatic.com              \$ssl_preread_server_name:443;
    .oaiusercontent.com         \$ssl_preread_server_name:443;
    .sora.com                   \$ssl_preread_server_name:443;

    # Google / Gemini (login path included, or Gemini loops on sign-in)
    .google.com                 \$ssl_preread_server_name:443;
    .googleapis.com             \$ssl_preread_server_name:443;
    .gstatic.com                \$ssl_preread_server_name:443;
    .googleusercontent.com      \$ssl_preread_server_name:443;
    .google                     \$ssl_preread_server_name:443;
    .ai.google.dev              \$ssl_preread_server_name:443;
    .withgoogle.com             \$ssl_preread_server_name:443;
    accounts.youtube.com        \$ssl_preread_server_name:443;

    # Anthropic / others
    .anthropic.com              \$ssl_preread_server_name:443;
    .claude.ai                  \$ssl_preread_server_name:443;
    .perplexity.ai              \$ssl_preread_server_name:443;
    .x.ai                       \$ssl_preread_server_name:443;
    .grok.com                   \$ssl_preread_server_name:443;
    .copilot.microsoft.com      \$ssl_preread_server_name:443;
    .githubcopilot.com          \$ssl_preread_server_name:443;
    .huggingface.co             \$ssl_preread_server_name:443;
    .midjourney.com             \$ssl_preread_server_name:443;
    .suno.com                   \$ssl_preread_server_name:443;
    .elevenlabs.io              \$ssl_preread_server_name:443;
    .cursor.com                 \$ssl_preread_server_name:443;
    .poe.com                    \$ssl_preread_server_name:443;
    .mistral.ai                 \$ssl_preread_server_name:443;
    .groq.com                   \$ssl_preread_server_name:443;
    .deepseek.com               \$ssl_preread_server_name:443;
    .qwen.ai                    \$ssl_preread_server_name:443;
}

server {
    listen ${PORT};
    ssl_preread on;
    resolver 1.1.1.1 8.8.8.8 ipv6=off valid=300s;
    resolver_timeout 5s;
    proxy_connect_timeout 10s;
    proxy_timeout 600s;
    proxy_pass \$ai_backend;
}
EOF

nginx -t
systemctl enable nginx
systemctl restart nginx

info "3/4 opening port ${PORT}"
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q active; then
  ufw allow "${PORT}/tcp"
fi

info "4/4 pinning AutoVless AI traffic to ${MY_IP}:${PORT}"
if [[ -f "${ENV_FILE}" ]]; then
  for KV in "AI_ROUTE=true" "AI_PROXY_IP=${MY_IP}:${PORT}"; do
    KEY="${KV%%=*}"
    if grep -q "^${KEY}=" "${ENV_FILE}"; then sed -i "s|^${KEY}=.*|${KV}|" "${ENV_FILE}"; else echo "${KV}" >> "${ENV_FILE}"; fi
  done
  green ".env: AI_PROXY_IP=${MY_IP}:${PORT}"
else
  red "${ENV_FILE} not found. Add AI_PROXY_IP=${MY_IP}:${PORT} to your .env by hand."
fi

info "self-test (should print ip=${MY_IP} and loc=${COUNTRY:-??})"
curl -s --max-time 10 --connect-to "chatgpt.com:443:127.0.0.1:${PORT}" https://chatgpt.com/cdn-cgi/trace | grep -E '^(ip|loc)=' || red "self-test failed: check 'journalctl -u nginx'"

green ""
green "Relay ready. Restart the bot: cd ${TARGET} && docker compose up -d --build"
green "Then in the bot press 'apply fresh IPs' on each panel so the new worker is uploaded."
